HTTP/1.1 101 Web Socket Protocol Handshake
Upgrade: websocket
Connection: Upgrade
WebSocket-Origin: some-host
WebSocket-Location: ws://some-host:8000
Sec-WebSocket-Accept: 3sJ7Wx7gC3ZcOcu0W6I+xBh0CtI=

